### ISSUE TITLE
Missing example file

### ISSUE THREAD

**Issue by perdiguero** [NoahHenrikKleinschmidt/qpcr#2]
Hi,

The "todays_qPCR_run.xlsx" file used in the readme is not in the example files folder.

It will be nice to know how the "groups" are organized in a multiple assay file with decorators and to run it to obtain the same results depicted in the readme. This is not evident in the example files available.

Thanks in advance,

**Comment by NoahHenrikKleinschmidt** [comment]
Heyhow, 

Yes, that's true, the file is not there. The file was actually just an abstract concept including the data from the example `csv` files. But I assembled the file for you and added to the Examples folder. I re-ran the snippet from the README-file and got the same figure out. The file is located at `Examples/todays_qPCR_run.xlsx` now. 
Hope this helps :-)

Cheers, Noah

**Comment by perdiguero** [comment]
Hi,

Wow Thanks for the prompt response. The examples helped a lot. Somehow, I was swapping the "name" and "Type" categories... 

Great software!
